#ifndef __UTILITIES__
#define __UTILITIES__
#define DESTINATION_BITS_LENGTH 3
enum CommandType { A_COMMAND, L_COMMAND, C_COMMAND };
enum CInstructionBits {
  INS_OP_CODE,
  INS_DEFAULT_1,
  INS_DEFAULT_2,
  INS_A_VALUE,
  INS_C1,
  INS_C2,
  INS_C3,
  INS_C4,
  INS_C5,
  INS_C6,
  INS_D1,
  INS_D2,
  INS_D3,
  INS_J1,
  INS_J2,
  INS_J3
};
enum C_INSTRUCTION_DEST {
  DEST_UNDEFINED = -1,
  DEST_null = 0,
  DEST_M = 1,
  DEST_D = 2,
  DEST_MD = 3,
  DEST_A = 4,
  DEST_AM = 5,
  DEST_AD = 6,
  DEST_AMD = 7
};
enum C_INSTRUCTION_COMP {
  C_INSTRUCTION_COMP_ZERO = 42,
  C_INSTRUCTION_COMP_ONE = 63,
  C_INSTRUCTION_COMP_MINUS_ONE = 58,
  C_INSTRUCTION_COMP_D = 12,
  C_INSTRUCTION_COMP_A = 48,
  C_INSTRUCTION_COMP_M = 112,
  C_INSTRUCTION_COMP_NOT_D = 13,
  C_INSTRUCTION_COMP_NOT_A = 49,
  C_INSTRUCTION_COMP_NOT_M = 113,
  C_INSTRUCTION_COMP_MINUS_D = 15,
  C_INSTRUCTION_COMP_MINUS_A = 51,
  C_INSTRUCTION_COMP_MINUS_M = 115,
  C_INSTRUCTION_COMP_D_PLUS_ONE = 31,
  C_INSTRUCTION_COMP_A_PLUS_ONE = 55,
  C_INSTRUCTION_COMP_M_PLUS_ONE = 119,
  C_INSTRUCTION_COMP_D_MINUS_ONE = 14,
  C_INSTRUCTION_COMP_A_MINUS_ONE = 50,
  C_INSTRUCTION_COMP_M_MINUS_ONE = 114,
  C_INSTRUCTION_COMP_D_PLUS_A = 2,
  C_INSTRUCTION_COMP_D_PLUS_M = 66,
  C_INSTRUCTION_COMP_D_MINUS_A = 19,
  C_INSTRUCTION_COMP_D_MINUS_M = 83,
  C_INSTRUCTION_COMP_A_MINUS_D = 7,
  C_INSTRUCTION_COMP_M_MINUS_D = 71,
  C_INSTRUCTION_COMP_D_ASP_A = 0,
  C_INSTRUCTION_COMP_D_ASP_M = 64,
  C_INSTRUCTION_COMP_D_PIPE_A = 21,
  C_INSTRUCTION_COMP_D_PIPE_M = 85
};
#endif
